= Cassandra Client for Vert.x

A Vert.x client allowing applications to interact with an http://cassandra.apache.org/[Apache Cassandra] service.

== Getting started

To use this module, add the following to the _dependencies_ section of your Maven POM file:

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-cassandra-client</artifactId>
  <version>${maven.version}</version>
</dependency>
----

Or, if you use Gradle:

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-cassandra-client:${maven.version}'
----

== Creating a client

=== Client options

Cassandra is a distributed system, and it can have many nodes.
To connect to Cassandra you need to specify the addresses of some cluster nodes when creating a {@link io.vertx.cassandra.CassandraClientOptions} object:

[source,$lang]
----
{@link examples.CassandraClientExamples#specifyingNodes}
----

By default, the Cassandra client for Vert.x connects to the local machine's port `9042` and is not tied to any specific keyspace.
But you can set either or both of these options:

[source,$lang]
----
{@link examples.CassandraClientExamples#portAndKeyspace}
----

TIP: For fine tuning purposes, {@link io.vertx.cassandra.CassandraClientOptions} exposes a `com.datastax.driver.core.Cluster.Builder` instance.

=== Shared clients

If you deploy multiple instances of your verticle or have different verticles interacting with the same database, it is recommended to create a shared client:

[source,$lang]
----
{@link examples.CassandraClientExamples#sharedClient}
----

Shared clients with the same name will use a single underlying `com.datastax.driver.core.Session`.

=== Client lifecycle

After the client is created, it is not connected until the first query is executed.

TIP: A shared client can be connected after creation if another client with the same name has already executed a query.

Clients created inside a verticle are automatically stopped when the verticle is undeployed.
In other words, you do not need to invoke {@link io.vertx.cassandra.CassandraClient#close} in the verticle `stop` method.

In all other cases, you must manually close the client.

NOTE: When a shared client is closed, the driver dession is not closed if other clients with the same name are still running.

== Using the API

The client API is represented by {@link io.vertx.cassandra.CassandraClient}.

=== Querying

You can get query results using three different ways.

==== Streaming

The streaming API is most appropriate when you need to consume results iteratively, e.g you want to process each item.
This is very efficient specially for large amount of rows.

In order to give you some inspiration and ideas on how you can use the API, we'd like to you to consider this example:

[source,$lang]
----
{@link examples.CassandraClientExamples#streamingViaHttp}
----

In the example, we are executing a query, and stream results via HTTP.

==== Bulk fetching

This API should be used when you need to process all the rows at the same time.

[source,$lang]
----
{@link examples.CassandraClientExamples#fetchAll}
----

CAUTION: Use bulk fetching only if you can afford to load the full result set in memory.

=== Collector queries

You can use Java collectors with the query API:

[source,$lang]
----
{@link examples.CassandraClientExamples#executeAndCollect}
----

==== Low level fetch

This API provides greater control over loading at the expense of being a bit lower-level than the streaming and bulk fetching APIs.

[source,$lang]
----
{@link examples.CassandraClientExamples#lowLevelQuerying}
----

=== Prepared queries

For security and efficiency reasons, it is a good idea to use prepared statements for all the queries you are using more than once.

You can prepare a query:

[source,$lang]
----
{@link examples.CassandraClientExamples#prepareQuery}
----

And then use the https://docs.datastax.com/en/drivers/java/${datastax.driver.minor.version}/com/datastax/driver/core/PreparedStatement.html[`PreparedStatement`] for all the next queries:

[source,$lang]
----
{@link examples.CassandraClientExamples#usingPreparedStatementFuture}
----

=== Batching

In case you'd like to execute several queries at once, you can use https://docs.datastax.com/en/drivers/java/${datastax.driver.minor.version}/com/datastax/driver/core/BatchStatement.html[`BatchStatement`] for that:

[source,$lang]
----
{@link examples.CassandraClientExamples#batching}
----

== Tracing queries

The Cassandra Client can trace query execution when Vert.x has tracing enabled.

The client reports the following _client_ spans:

* `Query` operation name
* tags
** `peer.address`: list of nodes known to the driver, in the form `[127_0_0_1:9042,localhost:9042,myhost_mydomain:9042]`
** `span.kind`: `client`
** `db.instance`: the keyspace
** `db.statement`: the CQL query
** `db.type`: `cassandra`

The default tracing policy is {@link io.vertx.core.tracing.TracingPolicy#PROPAGATE}, the client will only create a span when involved in an active trace.

You can change the client policy with {@link io.vertx.cassandra.CassandraClientOptions#setTracingPolicy}.
For example, you can set {@link io.vertx.core.tracing.TracingPolicy#ALWAYS} to always report a span:

[source,$lang]
----
{@link examples.CassandraClientExamples#tracing}
----

ifeval::["$lang" == "java"]
include::override/rxjava3.adoc[]
endif::[]
