= Cassandra Client for Vert.x

A Vert.x client allowing applications to interact with a Cassandra service.

== Using the Cassandra Client for Vert.x

To use this module, add the following to the _dependencies_ section of your Maven POM file:

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>${maven.groupId}</groupId>
  <artifactId>${maven.artifactId}</artifactId>
  <version>${maven.version}</version>
</dependency>
----

Or, if you use Gradle:

[source,groovy,subs="+attributes"]
----
compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
----

WARNING: the Cassandra client is not compatible with the Vert.x Dropwizard Metrics library. Both are using a different
major version of the Dropwizard Metrics library and the Cassandra driver https://github.com/datastax/java-driver/pull/943[won't upgrade]
to the most recent version due to the drop of Java 7. The next major version of the Cassandra driver (4)
will uses a more recent Dropwizard Metrics library  version.


== Creating a client

http://cassandra.apache.org/[Cassandra] is a distributed system, and it can have many nodes.
To connect to Cassandra you need to specify the addresses of some cluster nodes when creating a {@link io.vertx.cassandra.CassandraClientOptions} object:

[source,$lang]
----
{@link examples.CassandraClientExamples#specifyingNodes}
----

NOTE: By default, the Cassandra client for Vert.x will connect to the local machine's port `9042`.

=== Connect/Disconnect

After the client is created you can connect using specific cluster options:

[source,$lang]
----
{@link examples.CassandraClientExamples#connecting}
----

To disconnect, you can do it in a similar way:

[source,$lang]
----
{@link examples.CassandraClientExamples#disconnecting}
----

== Using the API

The client API is represented by {@link io.vertx.cassandra.CassandraClient}.

=== Querying

You can get query results using three different ways.

==== Streaming

The streaming API is most appropriate when you need to consume results iteratively, e.g you want to process each item.
This is very efficient specially for large amount of rows.

In order to give you some inspiration and ideas on how you can use the API, we'd like to you to consider this example:

[source,$lang]
----
{@link examples.CassandraClientExamples#streamingViaHttp}
----

In the example, we are executing a query, and stream results via HTTP.

==== Bulk fetching

This API should be used when you need to process all the rows at the same time.

[source,$lang]
----
{@link examples.CassandraClientExamples#fetchAll}
----

CAUTION: Use bulk fetching only if you can afford to load the full result set in memory.

==== Low level fetch

This API provides greater control over loading at the expense of being a bit lower-level than the streaming and bulk fetching APIs.

[source,$lang]
----
{@link examples.CassandraClientExamples#lowLevelQuerying}
----

=== Prepared queries

For security and efficiency reasons, it is a good idea to use prepared statements for all the queries you are using more than once.

You can prepare a query:

[source,$lang]
----
{@link examples.CassandraClientExamples#prepareQuery}
----

And then use the https://docs.datastax.com/en/drivers/java/${datastax-driver.minor.version}/com/datastax/driver/core/PreparedStatement.html[`PreparedStatement`] for all the next queries:

[source,$lang]
----
{@link examples.CassandraClientExamples#usingPreparedStatementFuture}
----

=== Batching

In case you'd like to execute several queries at once, you can use https://docs.datastax.com/en/drivers/java/${datastax-driver.minor.version}/com/datastax/driver/core/BatchStatement.html[`BatchStatement`] for that:

[source,$lang]
----
{@link examples.CassandraClientExamples#batching}
----
